### ISSUE TITLE
Make the Bone texture rainbow

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/pridebones#4]
Due to the pack literally being called "Pride Bones", we should make actual bone textures be themed.
Suggested by @SympathyTea [on the discord](https://discord.com/channels/1091969030694375444/1092235223804157982/1270396913354674289)

**Comment by blryface** [comment]
wuh when did I self assign

**Comment by blryface** [comment]
this was 3 months ago??
I don't think we should change bones

**Comment by Laxystem** [comment]
character growth be like
